version: "3.9"

services:
  daemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thothos_daemon
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 main.py
